//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherUpdateWebApp.WeatherServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherServiceProxy.IWeatherService")]
    public interface IWeatherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/getWeatherUpdate", ReplyAction="http://tempuri.org/IWeatherService/getWeatherUpdateResponse")]
        string getWeatherUpdate(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/getWeatherUpdate", ReplyAction="http://tempuri.org/IWeatherService/getWeatherUpdateResponse")]
        System.Threading.Tasks.Task<string> getWeatherUpdateAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/getWeatherUpdate2", ReplyAction="http://tempuri.org/IWeatherService/getWeatherUpdate2Response")]
        string[] getWeatherUpdate2(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/getWeatherUpdate2", ReplyAction="http://tempuri.org/IWeatherService/getWeatherUpdate2Response")]
        System.Threading.Tasks.Task<string[]> getWeatherUpdate2Async(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherServiceChannel : WeatherUpdateWebApp.WeatherServiceProxy.IWeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceClient : System.ServiceModel.ClientBase<WeatherUpdateWebApp.WeatherServiceProxy.IWeatherService>, WeatherUpdateWebApp.WeatherServiceProxy.IWeatherService {
        
        public WeatherServiceClient() {
        }
        
        public WeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getWeatherUpdate(string city) {
            return base.Channel.getWeatherUpdate(city);
        }
        
        public System.Threading.Tasks.Task<string> getWeatherUpdateAsync(string city) {
            return base.Channel.getWeatherUpdateAsync(city);
        }
        
        public string[] getWeatherUpdate2(string city) {
            return base.Channel.getWeatherUpdate2(city);
        }
        
        public System.Threading.Tasks.Task<string[]> getWeatherUpdate2Async(string city) {
            return base.Channel.getWeatherUpdate2Async(city);
        }
    }
}
