//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeDataWebApp.CrimeDataProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrimeDataProxy.ICrimeDataService")]
    public interface ICrimeDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrimeDataService/getCrimeData", ReplyAction="http://tempuri.org/ICrimeDataService/getCrimeDataResponse")]
        string getCrimeData(string lat, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrimeDataService/getCrimeData", ReplyAction="http://tempuri.org/ICrimeDataService/getCrimeDataResponse")]
        System.Threading.Tasks.Task<string> getCrimeDataAsync(string lat, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrimeDataService/getTotalCrimes", ReplyAction="http://tempuri.org/ICrimeDataService/getTotalCrimesResponse")]
        int getTotalCrimes(string lat, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrimeDataService/getTotalCrimes", ReplyAction="http://tempuri.org/ICrimeDataService/getTotalCrimesResponse")]
        System.Threading.Tasks.Task<int> getTotalCrimesAsync(string lat, string lang);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrimeDataServiceChannel : CrimeDataWebApp.CrimeDataProxy.ICrimeDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrimeDataServiceClient : System.ServiceModel.ClientBase<CrimeDataWebApp.CrimeDataProxy.ICrimeDataService>, CrimeDataWebApp.CrimeDataProxy.ICrimeDataService {
        
        public CrimeDataServiceClient() {
        }
        
        public CrimeDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrimeDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrimeDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrimeDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCrimeData(string lat, string lang) {
            return base.Channel.getCrimeData(lat, lang);
        }
        
        public System.Threading.Tasks.Task<string> getCrimeDataAsync(string lat, string lang) {
            return base.Channel.getCrimeDataAsync(lat, lang);
        }
        
        public int getTotalCrimes(string lat, string lang) {
            return base.Channel.getTotalCrimes(lat, lang);
        }
        
        public System.Threading.Tasks.Task<int> getTotalCrimesAsync(string lat, string lang) {
            return base.Channel.getTotalCrimesAsync(lat, lang);
        }
    }
}
